In [2]:
cd ..

/Users/vijay/vijaygkd/deep-ttt


In [438]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as k
import mlflow

In [6]:
#%load_ext autoreload
%autoreload 2

In [4]:
from dqn.environment import *
from dqn.agent import RandomAgent, QAgent
from dqn.model import DQN
from dqn.train import Memory, QLearning


In [492]:
t = QLearning()

hey4


In [493]:
t.net.model.summary()

Model: "model_36"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_states (InputLayer)      [(None, 9)]          0           []                               
                                                                                                  
 hidden_1 (Dense)               (None, 64)           640         ['input_states[0][0]']           
                                                                                                  
 hidden_2 (Dense)               (None, 32)           2080        ['hidden_1[0][0]']               
                                                                                                  
 output (Dense)                 (None, 9)            297         ['hidden_2[0][0]']               
                                                                                           

In [494]:
with mlflow.start_run(run_name='test run 5 - fix metrics') as run:
    t.train(10000)

100%|█████████████████████████████████████████████████████████████████| 10000/10000 [1:27:52<00:00,  1.90it/s]


In [495]:
with mlflow.start_run(run_name='test run 5 - fix metrics - 2') as run:
    t.train(20000)

100%|█████████████████████████████████████████████████████████████████| 20000/20000 [1:24:09<00:00,  3.96it/s]


In [496]:
board_samples

[array([[ 0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  1.]]),
 array([6., 1., 5., 3., 5.]),
 array([-0.1, -0.1, -0.1, -0.1, -5. ]),
 array([[ 0.,  0., -1.,  0.,  1.,  0.,  1.,  0.,  0.],
        [ 0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.,  0., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  1.]]),
 array([0., 0., 0., 0., 0.])]

In [497]:
ans = t.net.model.predict([board_samples[0], board_samples[1]])
ans

1/1 [==============================] - 0s 17ms/step


[array([6, 1, 5, 0, 2]),
 array([ 0.3141801 , -0.24979544, -0.11569901,  0.44423825, -0.10521524],
       dtype=float32)]

In [559]:
g = TicTacToe()

In [582]:
g.execute_action(8)

(-5, 1)

In [583]:
g.print_board()

X O O 

O X - 

X - X 



In [584]:
t.net.model.predict([g.get_current_state().reshape(1,9), np.array([-1])])

1/1 [==============================] - 0s 11ms/step


[array([8]), array([0.16187888], dtype=float32)]