In [2]:
cd ..

/Users/vijay/vijaygkd/deep-ttt


In [29]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import backend as k


In [6]:
#%load_ext autoreload
%autoreload 2

In [4]:
from dqn.environment import *
from dqn.agent import RandomAgent, QAgent
from dqn.model import DQN
from dqn.train import Memory, QLearning


In [411]:
t = QLearning()

hey3


In [412]:
t.net.model.summary()

Model: "model_22"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_states (InputLayer)      [(None, 9)]          0           []                               
                                                                                                  
 hidden_1 (Dense)               (None, 64)           640         ['input_states[0][0]']           
                                                                                                  
 hidden_2 (Dense)               (None, 32)           2080        ['hidden_1[0][0]']               
                                                                                                  
 output (Dense)                 (None, 9)            297         ['hidden_2[0][0]']               
                                                                                           

In [413]:
t.train(episodes=5)

100%|██████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 250.56it/s]


INFO:tensorflow:Assets written to: dqn_net/assets


In [414]:
old_wts = t.net.model.layers[3].get_weights().copy()

In [419]:
t.do_gradient_update(32)

[[ 0. -1.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.  0. -1.]
 [ 1.  0.  0.  1.  0.  0.  0. -1.  0.]
 [ 0. -1.  0. -1.  0.  1.  0.  1.  1.]
 [ 0. -1.  0. -1.  0.  1. -1.  1.  1.]
 [ 0.  0. -1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -1.  1.  1.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1. -1.  1. -1.  1.  0. -1. -1.]
 [ 1.  0. -1.  1. -1.  1.  0. -1.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0. -1.  1. -1.  1.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  1.  0.  0. -1. -1.  0.]
 [ 0. -1.  0.  1. -1.  1.  1.  1. -1.]
 [ 0. -1.  0. -1.  0.  1.  0.  1.  1.]
 [ 0.  0.  0.  0. -1.  1.  1.  0. -1.]
 [ 0.  1. -1. -1.  0.  1.  0.  1.  0.]
 [ 1.  1. -1.  1. -1.  1.  0. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  1. -1.  1.  1.  1. -1.]
 [ 0. -1.  0.  1. -1.  1.  1.  1. -1.]
 [ 0.  1. -1. -1.  0.  1.  0.  1.  0.]
 [ 1.  1. -1.  1. -1.  1.  0. -1.  0.]
 [ 0.  1. -1. -1.  0.  1.  0.  1.  0.]
 [ 0.  0. -1. -1.  0.  1.

In [402]:
new_wts = t.net.model.layers[3].get_weights().copy()

In [416]:
0.020972846 - 0.1

-0.079027154

In [403]:
np.array_equal(old_wts[0], new_wts[0])

False

In [404]:
(old_wts[0] - new_wts[0])#[:,0]

array([[0.00029984, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.00029993, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.00029996, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.00029975, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.00029996, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [405]:
old_wts[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [406]:
new_wts[1]

array([-0.00029999,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ], dtype=float32)

In [410]:
1 - board_samples[4]

array([1., 1., 1., 1., 1.])

In [252]:
board_samples = t.memory.sample_records(5)

In [253]:
board_samples[0].shape

(5, 9)

In [254]:
board_samples

[array([[ 0.,  1., -1., -1.,  1.,  1., -1.,  0.,  0.],
        [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1., -1.,  0., -1., -1.,  1.,  1.,  0.],
        [-1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]]),
 array([8., 1., 3., 8., 2.]),
 array([-1. , -0.1, -0.1, -1. , -0.1]),
 array([[ 0.,  1., -1., -1.,  1.,  1., -1.,  0.,  1.],
        [-1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1., -1.,  0., -1., -1.,  1.,  1., -1.],
        [-1.,  1., -1.,  0.,  0.,  0.,  1.,  0.,  0.]]),
 array([0., 0., 0., 0., 0.])]

In [255]:
ans1 = t.net.model([board_samples[0], board_samples[1]], training=True)
ans1

[<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
 array([[8],
        [1],
        [3],
        [8],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
 array([[-0.15436232],
        [-0.06692867],
        [ 0.03474152],
        [-0.53856516],
        [-0.20140201]], dtype=float32)>]

In [256]:
ans = t.net.model.predict([board_samples[0], board_samples[1]])
ans

1/1 [==============================] - 0s 15ms/step


[array([6, 6, 6, 6, 6]),
 array([0.2774571 , 0.19662073, 0.23035435, 0.70684135, 0.45960778],
       dtype=float32)]

In [257]:
ans1[0].numpy().shape

(5, 1)

In [246]:
ans[0].shape

(5,)