In [1]:
cd ..

/Users/vijay/vijaygkd/deep-ttt


In [2]:
import numpy as np
import tensorflow as tf

In [29]:
#%load_ext autoreload
%autoreload 2

In [3]:
from dqn.environment import *
from dqn.agent import RandomAgent, QAgent
from dqn.model import DQN
from dqn.train import Memory, QLearning


2022-08-27 20:07:20.242233: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [33]:
t = QLearning()

hey2


In [34]:
t.net.model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_states (InputLayer)      [(None, 9)]          0           []                               
                                                                                                  
 hidden_1 (Dense)               (None, 64)           640         ['input_states[0][0]']           
                                                                                                  
 hidden_2 (Dense)               (None, 32)           2080        ['hidden_1[0][0]']               
                                                                                                  
 output (Dense)                 (None, 9)            297         ['hidden_2[0][0]']               
                                                                                            

In [44]:
t.train(episodes=500)

 67%|███████████████████████████████████████████████▎                       | 333/500 [02:20<01:10,  2.38it/s]

KeyboardInterrupt



In [45]:
t.net.model.get_weights()

[array([[-2.75973797e-01,  1.58070654e-01, -5.68869188e-02,
         -1.70184717e-01,  2.58196503e-01,  9.47250128e-02,
          1.04761040e-02, -1.70516670e-01, -2.51267403e-01,
          5.20849861e-02,  1.26718059e-01,  2.19971195e-01,
         -3.17703225e-02, -2.72053778e-01, -1.95546061e-01,
          4.26897891e-02,  4.77881692e-02,  1.07655451e-01,
          2.75492430e-01,  8.96090418e-02,  8.48468840e-02,
         -1.84825554e-01, -2.76243359e-01,  1.68110088e-01,
         -1.04177706e-01,  2.07127128e-02,  2.17373431e-01,
         -8.96501243e-02,  1.83576316e-01, -3.18488479e-02,
         -9.12923962e-02, -2.14628443e-01, -2.26648599e-01,
         -2.79417425e-01,  5.61184585e-02, -5.10832183e-02,
         -1.78443253e-01, -1.61688074e-01,  9.31385681e-02,
         -1.81268290e-01,  1.99301168e-02, -1.53506294e-01,
         -2.13264704e-01,  2.43370831e-01,  3.57819349e-02,
         -2.31335625e-01, -1.94186568e-01,  2.41725400e-01,
          1.24315292e-01, -3.19995731e-0

In [48]:
board_samples = t.memory.sample_records(5)

In [49]:
board_samples[0].shape

(5, 9)

In [50]:
board_samples

[array([[-1.,  1., -1.,  1.,  0.,  0.,  1., -1.,  1.],
        [-1.,  1.,  1.,  0., -1.,  1.,  1., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0., -1., -1., -1.,  1.,  1., -1.,  1.]]),
 array([4., 2., 6., 6., 1.]),
 array([-0.1, -5. , -0.1, -0.1,  0.5]),
 array([[-1.,  1., -1.,  1., -1.,  0.,  1., -1.,  1.],
        [-1.,  1.,  1.,  0., -1.,  1.,  1., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.]]),
 array([0., 0., 0., 0., 1.])]

In [52]:
ans = t.net.model.predict([board_samples[0], board_samples[1]])
ans

1/1 [==============================] - 0s 45ms/step


array([4, 1, 1, 1, 1])

In [23]:
boards = np.array([[-1.,  0.,  0.,  1., -1.,  1.,  0., -1.,  1.],
        [ 1.,  1.,  0.,  1., -1.,  0., -1.,  0., -1.],
        [ 1., -1.,  1.,  0.,  1.,  0.,  0., -1.,  0.],
        [ 0., -1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.],
        [-1.,  1.,  0., -1.,  1.,  0.,  1., -1.,  0.]])
indices = np.array([-1,-1,3,-3,-2]).reshape(5,1)

ans = training.net.model.predict([boards, indices])
ans

1/1 [==============================] - 0s 14ms/step


array([0, 0, 0, 0, 0])

1/1 [==============================] - 0s 16ms/step


In [496]:
ans

array([4, 5, 7, 0, 7])

In [324]:
mask = tf.Variable(initial_value=tf.zeros((9,)), trainable=False)

In [362]:
mask

<tf.Variable 'Variable:0' shape=(9,) dtype=float32, numpy=array([0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)>

In [360]:
d = tf.Variable(initial_value=tf.random.uniform((4,9)), trainable=False)

In [361]:
d

<tf.Variable 'Variable:0' shape=(4, 9) dtype=float32, numpy=
array([[0.22870278, 0.13965893, 0.6911694 , 0.56706154, 0.41751945,
        0.86489177, 0.43477118, 0.2735579 , 0.32573032],
       [0.49296308, 0.11750197, 0.310488  , 0.04569244, 0.34075046,
        0.66507053, 0.17342031, 0.38271046, 0.13883793],
       [0.6610012 , 0.48059058, 0.04759991, 0.08220959, 0.34939456,
        0.15660644, 0.80975413, 0.23500586, 0.9344349 ],
       [0.21887791, 0.76104176, 0.8053353 , 0.06729019, 0.45567894,
        0.6191101 , 0.5588839 , 0.7538363 , 0.51985705]], dtype=float32)>

In [369]:
d[3]

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.21887791, 0.76104176, 0.8053353 , 0.06729019, 0.45567894,
       0.6191101 , 0.5588839 , 0.7538363 , 0.51985705], dtype=float32)>

In [363]:
d * mask

<tf.Tensor: shape=(4, 9), dtype=float32, numpy=
array([[0.        , 0.        , 0.        , 0.56706154, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.04569244, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.08220959, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.06729019, 0.        ,
        0.        , 0.        , 0.        , 0.        ]], dtype=float32)>

In [364]:
tf.reduce_sum(d * mask, axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.56706154, 0.04569244, 0.08220959, 0.06729019], dtype=float32)>

In [371]:
tf.argmax(d, axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 5, 8, 2])>

In [486]:
mask.type

<tf.Variable 'Variable:0' shape=(9,) dtype=float32, numpy=array([0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)>

In [332]:
mask[3].assign(1)

<tf.Variable 'UnreadVariable' shape=(9,) dtype=float32, numpy=array([0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)>

In [333]:
mask

<tf.Variable 'Variable:0' shape=(9,) dtype=float32, numpy=array([0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)>

In [376]:
r = tf.random.uniform([4,9],0, 9, dtype=tf.int32)
i = tf.random.uniform([4], 0, 9, dtype=tf.int32)
tf.gather(r, i, axis=1, batch_dims=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 6, 3, 7], dtype=int32)>

In [377]:
r

<tf.Tensor: shape=(4, 9), dtype=int32, numpy=
array([[1, 0, 1, 7, 3, 8, 6, 5, 5],
       [3, 0, 6, 6, 3, 0, 8, 1, 3],
       [6, 7, 2, 0, 3, 4, 2, 6, 1],
       [8, 1, 7, 8, 8, 8, 3, 2, 2]], dtype=int32)>

In [378]:
i

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 3, 4, 2], dtype=int32)>

In [379]:
tf.gather(r, i, axis=1, batch_dims=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 6, 3, 7], dtype=int32)>